import { expect, test } from '@playwright/test';

test('annotates local attachments with single-step undo, save and cancel', async ({ page }, info) => {
  await page.route('https://fonts.googleapis.com/**', (route) => route.abort());
  await page.goto('/e2e/image-attachments-harness.html');
  const thumbnail = page.getByRole('img', { name: '图片 1：截图.png' });
  const original = await thumbnail.getAttribute('src');
  await page.getByRole('button', { name: '标注图片 1', exact: true }).click();
  const editor = page.frameLocator('iframe');
  const done = editor.getByRole('button', { name: '完成', exact: true });
  await expect(done).toBeEnabled();
  const canvas = editor.locator('canvas');
  const snapshot = () => canvas.evaluate((element: HTMLCanvasElement) => element.toDataURL());
  const clean = await snapshot();
  await canvas.click({ position: { x: 80, y: 80 } });
  const first = await snapshot();
  await editor.getByRole('button', { name: '箭头', exact: true }).click();
  const bounds = (await canvas.boundingBox())!;
  await page.mouse.move(bounds.x + 180, bounds.y + 180);
  await page.mouse.down();
  await page.mouse.move(bounds.x + 300, bounds.y + 250, { steps: 10 });
  await page.mouse.up();
  expect(await snapshot()).not.toBe(first);
  await page.keyboard.press('Control+z');
  expect(await snapshot()).toBe(first);
  await page.keyboard.press('Control+z');
  expect(await snapshot()).toBe(clean);
  await editor.getByRole('button', { name: '重做', exact: true }).click();
  expect(await snapshot()).toBe(first);
  await page.screenshot({ path: info.outputPath('local-image-editor.png') });
  await done.click();
  await expect(page.locator('iframe')).toHaveCount(0);
  await expect(thumbnail).toHaveAttribute('src', /^data:image\/jpeg;base64,/);
  const edited = await thumbnail.getAttribute('src');
  expect(edited).not.toBe(original);
  await page.getByRole('button', { name: '标注图片 1', exact: true }).click();
  await expect(done).toBeEnabled();
  await canvas.click();
  await editor.getByRole('button', { name: '取消', exact: true }).click();
  await expect(page.locator('iframe')).toHaveCount(0);
  await expect(thumbnail).toHaveAttribute('src', edited!);
  await expect(page.getByRole('textbox', { name: '消息' })).toHaveValue('请看图片中圈出的部分');
});
