import { createThemedStyles } from '../../theme/styles';

export const useDisplaySettingsStyles = createThemedStyles((color) => ({
  panel: { position: 'absolute', top: 8, right: 8, bottom: 8, width: '94%', maxWidth: 400,
    minHeight: 0, backgroundColor: '#1d2633', borderWidth: 1, borderColor: color('#2b3645', 'border'),
    borderRadius: 16, overflow: 'hidden' },
  header: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, flexShrink: 0 },
  compactHeader: { paddingVertical: 6, paddingHorizontal: 14 },
  compactTitle: { fontSize: 16 },
  headerCopy: { flex: 1, minWidth: 0 },
  title: { color: '#eef3fc', fontSize: 20, lineHeight: 28, fontWeight: '600' },
  close: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  scroll: { flex: 1, minHeight: 0 },
  content: { gap: 10, paddingHorizontal: 14, paddingBottom: 14 },
  section: { paddingVertical: 14, paddingHorizontal: 12, borderWidth: 1, borderColor: color('#303b4b', 'border'),
    borderRadius: 12, backgroundColor: '#ffffff03' },
  sectionHeading: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 12 },
  sectionTitle: { color: '#eef3fc', fontSize: 14, lineHeight: 21, fontWeight: '600', marginBottom: 3 },
  description: { color: color('#aab6c9', 'faint'), fontSize: 12, lineHeight: 19 },
  text: { color: '#eef3fc', fontSize: 14, lineHeight: 21 },
  monitorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 12 },
  monitorCard: { flexBasis: '45%', flexGrow: 1, minWidth: 0, alignItems: 'center',
    paddingTop: 22, paddingHorizontal: 8, paddingBottom: 10, borderWidth: 2, borderColor: color('#3b4657', 'border'),
    borderRadius: 11, backgroundColor: '#12192355' },
  monitorSelected: { borderColor: color('#589cff', 'info'), backgroundColor: '#26384b55' },
  monitorCheck: { position: 'absolute', top: 7, right: 7, width: 17, height: 17,
    borderRadius: 9, borderWidth: 1.5, borderColor: color('#616e82', 'border'), alignItems: 'center', justifyContent: 'center' },
  monitorChecked: { backgroundColor: '#4d94f8', borderColor: color('#4d94f8', 'info') },
  monitorPreview: { width: '78%', maxWidth: 104, aspectRatio: 16 / 9, backgroundColor: '#398afa',
    borderWidth: 1, borderColor: color('#a5c7f5', 'border'), borderRadius: 3, overflow: 'hidden', marginBottom: 10 },
  monitorWave: { position: 'absolute', width: '150%', height: '100%', left: '-8%', top: '50%',
    borderRadius: 70, transform: [{ rotate: '-24deg' }], backgroundColor: '#1957a8' },
  monitorShine: { position: 'absolute', width: '150%', height: '100%', left: '-50%', top: '15%',
    borderRadius: 70, transform: [{ rotate: '20deg' }], backgroundColor: '#7abaff45' },
  monitorName: { color: '#eef3fc', fontSize: 13, lineHeight: 20, textAlign: 'center' },
  monitorResolution: { color: color('#aab6c9', 'faint'), fontSize: 12, lineHeight: 19, textAlign: 'center' },
  toggle: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12,
    borderWidth: 1, borderColor: '#ffffff03', borderRadius: 10, backgroundColor: '#ffffff04' },
  toggleDescription: { color: color('#aab6c9', 'faint'), fontSize: 11, lineHeight: 18, marginTop: 2 },
  switchTrack: { width: 34, height: 20, borderRadius: 12, padding: 2, backgroundColor: '#3d4a5c' },
  switchOn: { backgroundColor: '#4d8feb' },
  switchThumb: { width: 16, height: 16, borderRadius: 8, backgroundColor: color('#b6c4dc', 'infoSoft') },
  switchThumbOn: { transform: [{ translateX: 14 }], backgroundColor: color('#fff', 'surface') },
  options: { flexDirection: 'row', gap: 6, marginBottom: 12 },
  choice: { flex: 1, minWidth: 0, minHeight: 38, alignItems: 'center', justifyContent: 'center',
    paddingVertical: 9, paddingHorizontal: 2, borderWidth: 2, borderColor: color('#3c4859', 'border'),
    borderRadius: 9, backgroundColor: '#ffffff04' },
  selected: { borderColor: color('#589cff', 'info'), backgroundColor: '#31568688' },
  choiceText: { color: '#eef3fc', fontSize: 12, lineHeight: 18, textAlign: 'center' },
  disabled: { opacity: 0.5 },
  custom: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 12 },
  input: { width: 80, color: '#eef3fc', fontSize: 16, paddingVertical: 9, paddingHorizontal: 10,
    borderWidth: 1, borderColor: color('#414e61', 'border'), borderRadius: 9, backgroundColor: '#12192388' },
  apply: { paddingVertical: 10, paddingHorizontal: 20, borderRadius: 9, backgroundColor: '#2e5280' },
  hint: { flexDirection: 'row', alignItems: 'flex-start', gap: 9 },
  hintText: { flex: 1, color: color('#aab6c9', 'faint'), fontSize: 11, lineHeight: 19 },
  error: { color: color('#ffadb2', 'danger'), fontSize: 12, lineHeight: 19 },
  instructions: { gap: 3, paddingVertical: 10, paddingHorizontal: 12, borderWidth: 1,
    borderColor: color('#364254', 'border'), borderRadius: 10, backgroundColor: '#ffffff03' },
  instruction: { flexDirection: 'row', gap: 8, alignItems: 'flex-start' },
  bullet: { color: color('#a8c8ff', 'info'), fontSize: 12, lineHeight: 22 },
  instructionText: { flex: 1, color: color('#aab6c9', 'faint'), fontSize: 12, lineHeight: 22 },
}));
