import { createThemedStyles } from '../../theme/styles';

export const useTerminalStyles = createThemedStyles((color) => ({
  container: { flex: 1 },
  button: { width: 44, height: 44, flexShrink: 0, alignItems: 'center', justifyContent: 'center' },
  disabled: { opacity: .4 },
  overlay: { flex: 1, backgroundColor: '#0006', justifyContent: 'flex-end' },
  fullscreenOverlay: { backgroundColor: color('#fff', 'surface'), justifyContent: 'flex-start' },
  backdrop: { flex: 1 },
  drawer: { height: '90%', backgroundColor: color('#fff', 'surface'), borderTopLeftRadius: 18, borderTopRightRadius: 18,
    overflow: 'hidden' },
  fullscreen: { flex: 1, flexShrink: 1, height: 'auto', minHeight: 0,
    borderTopLeftRadius: 0, borderTopRightRadius: 0 },
  wrapButton: { width: 54, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 8 },
  wrapLabel: { color: color('#718078', 'muted'), fontSize: 10, marginTop: 2 },
  selected: { backgroundColor: color('#eef4f1', 'canvas') },
  header: { flexDirection: 'row', flexShrink: 0, alignItems: 'center', padding: 10, gap: 6,
    borderBottomWidth: 1, borderBottomColor: color('#dfe5df', 'border') },
  compactHeader: { paddingVertical: 4 },
  inlineTabs: { flex: 1, maxWidth: 160, minWidth: 0 },
  inlineKeys: { flex: 2, minWidth: 0 },
  keyItems: { flexGrow: 1, alignItems: 'center', gap: 4 },
  key: { flex: 1, minWidth: 40, height: 44, paddingHorizontal: 8, borderRadius: 8,
    alignItems: 'center', justifyContent: 'center', backgroundColor: color('#eef4f1', 'canvas') },
  heading: { flex: 1, minWidth: 0, paddingLeft: 6 },
  title: { color: color('#17211b', 'ink'), fontSize: 16, fontWeight: '600' },
  subtitle: { color: color('#718078', 'muted'), fontSize: 11, marginTop: 4 },
  screen: { flex: 1, backgroundColor: color('#fff', 'surface') },
  tabs: { flexGrow: 0, flexShrink: 0, borderBottomWidth: 1, borderBottomColor: color('#dfe5df', 'border') },
  tabItems: { alignItems: 'center', paddingHorizontal: 10, gap: 6 },
  tab: { paddingHorizontal: 14, minHeight: 40, justifyContent: 'center', borderRadius: 8 },
  tabLabel: { color: color('#17211b', 'ink'), fontSize: 12 },
  loading: { flex: 1 },
  status: { maxWidth: 400, alignSelf: 'center', fontSize: 12, color: color('#718078', 'muted'), padding: 10 },
}));
