const contextSettingsCopy = {
  zh: {
    title: "对话上下文设置", gear: "当前对话容量设置", cancel: "取消", save: "保存", saving: "正在保存…",
    loading: "正在读取设置…", label: "上下文容量（K Token）", reset: "恢复默认", retry: "重试",
    hint: "仅用于当前对话。保存后立即应用；正在回复时会先暂停，修改后自动继续。",
    placeholder: "选择或输入容量，留空使用默认值", unit: "1 K = 1000 Token；留空使用默认容量。",
    usage: "用量会在收到回复后更新。可用容量受模型上限和预留空间影响。",
    invalid: "请输入 1 到 100000 之间的容量，最多保留三位小数。",
    readError: "暂时无法读取当前对话设置，请稍后重试。",
    saveError: "未能应用容量设置，请重试。如果回复已暂停，可以发送消息继续。",
    paused: "容量已保存，对话保持暂停。发送消息即可继续。",
    resumeFailed: "容量已保存，但未能自动继续。请发送消息继续。",
    saved: value => `对话设置：${value} Token`,
    lastUsage: "上方用量来自最近一次回复；可用容量会扣除预留空间。",
  },
  en: {
    title: "Conversation context settings", gear: "Current conversation capacity", cancel: "Cancel", save: "Save",
    saving: "Saving…", loading: "Loading settings…", label: "Context capacity (K tokens)", reset: "Reset to default",
    retry: "Retry", hint: "Applies only to this conversation. Saving pauses an active reply, applies the change, then continues.",
    placeholder: "Choose or enter a capacity; leave blank for default", unit: "1 K = 1000 tokens. Leave blank for default.",
    usage: "Usage updates after a reply. Available capacity depends on model limits and reserved space.",
    invalid: "Enter a capacity from 1 to 100000, with up to three decimal places.",
    readError: "Could not read this conversation’s settings. Please retry.",
    saveError: "Could not apply capacity. Please retry. If the reply paused, send a message to continue.",
    paused: "Capacity saved. The conversation remains paused. Send a message to continue.",
    resumeFailed: "Capacity saved, but the reply could not continue. Send a message to continue.",
    saved: value => `Conversation setting: ${value} tokens`,
    lastUsage: "Usage is from the last reply; available capacity excludes reserved space.",
  },
  ru: {
    title: "Настройки контекста диалога", gear: "Размер контекста текущего диалога", cancel: "Отмена", save: "Сохранить",
    saving: "Сохранение…", loading: "Загрузка настроек…", label: "Размер контекста (K токенов)", reset: "По умолчанию",
    retry: "Повторить", hint: "Только для этого диалога. Текущий ответ будет приостановлен и продолжен после изменения.",
    placeholder: "Выберите или введите размер; пустое поле — по умолчанию", unit: "1 K = 1000 токенов. Пусто — по умолчанию.",
    usage: "Расход обновится после ответа. Доступный размер зависит от модели и зарезервированного места.",
    invalid: "Введите число от 1 до 100000, не более трёх знаков после точки.",
    readError: "Не удалось загрузить настройки диалога. Повторите попытку.",
    saveError: "Не удалось применить размер. Повторите попытку. Если ответ остановлен, отправьте сообщение.",
    paused: "Размер сохранён. Диалог приостановлен. Отправьте сообщение, чтобы продолжить.",
    resumeFailed: "Размер сохранён, но ответ не продолжился. Отправьте сообщение, чтобы продолжить.",
    saved: value => `Настройка диалога: ${value} токенов`,
    lastUsage: "Расход указан для последнего ответа; доступный размер не включает резерв.",
  },
};
