import { createThemedStyles } from '../../theme/styles';
import { Platform,  } from 'react-native';
import { palette } from '../styles';
import { GRAPH_ROW_HEIGHT } from '../../../../../shared/remote-chat/gitGraph';

export const useGitStyles = createThemedStyles((color) => ({
  fill: { flex: 1, minWidth: 0 },
  toolbar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, gap: 8 },
  branch: { flexShrink: 1, fontSize: 14, fontWeight: '700', color: color(palette.ink, 'ink') },
  branchButton: { flex: 1, minWidth: 0, minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 8 },
  syncButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8 },
  tracking: { paddingHorizontal: 16, paddingBottom: 6, color: color(palette.muted, 'muted'), fontSize: 11 },
  viewToggle: { flexDirection: 'row', gap: 2, padding: 3, backgroundColor: color('#f2f5f3', 'canvas'), borderRadius: 8 },
  modeButton: { paddingHorizontal: 9, minHeight: 30, justifyContent: 'center', borderRadius: 6 },
  activeMode: { backgroundColor: color('#dcefe6', 'elevated') },
  activeViewMode: { backgroundColor: color('#fff', 'surface') },
  areaTitle: { fontSize: 12, fontWeight: '700', color: color(palette.ink, 'ink'), paddingVertical: 8 },
  areaRow: { marginTop: 4, backgroundColor: color('#f8faf9', 'canvas') },
  areaHeading: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
  areaDot: { width: 5, height: 5, borderRadius: 3 },
  areaCount: { marginLeft: 'auto', fontSize: 10, minWidth: 22, textAlign: 'center',
    paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, overflow: 'hidden' },
  menu: { position: 'absolute', top: 48, zIndex: 20, maxWidth: 400, width: '92%', alignSelf: 'center',
    borderWidth: 1, borderColor: color(palette.border, 'border'), borderRadius: 10, padding: 12,
    backgroundColor: color('#fafcfb', 'surface'), elevation: 8, boxShadow: '0 4px 20px #17211b22' },
  menuHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  menuScroll: { maxHeight: 320 },
  menuHint: { maxWidth: 400, fontSize: 12, lineHeight: 18, color: color(palette.muted, 'muted'), marginVertical: 8 },
  branchRow: { minHeight: 44, gap: 5, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: color('#edf1ef', 'border') },
  search: { padding: 10, borderWidth: 1, borderColor: color(palette.border, 'border'), borderRadius: 6,
    fontSize: 12, color: color(palette.ink, 'ink') },
  actionOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  actionButton: { padding: 10, borderRadius: 6, borderWidth: 1, borderColor: color(palette.border, 'border') },
  button: { padding: 12, alignItems: 'center', justifyContent: 'center' },
  buttonText: { fontSize: 13, color: color(palette.green, 'accent'), fontWeight: '600' },
  project: { paddingHorizontal: 16, paddingBottom: 10, fontSize: 11, color: color(palette.muted, 'muted') },
  notice: { maxWidth: 400, marginHorizontal: 16, marginVertical: 8,
    fontSize: 12, lineHeight: 18, color: color(palette.muted, 'muted') },
  error: { maxWidth: 400, marginHorizontal: 16, marginVertical: 8,
    fontSize: 12, lineHeight: 18, color: color(palette.danger, 'danger') },
  tabs: { flexDirection: 'row', marginHorizontal: 16, padding: 3, gap: 4,
    backgroundColor: color('#f2f5f3', 'canvas'), borderRadius: 10 },
  tab: { flex: 1, minHeight: 38, justifyContent: 'center', alignItems: 'center', borderRadius: 8 },
  selectedTab: { backgroundColor: color('#fff', 'surface'), boxShadow: '0 1px 3px #17211b0d' },
  tabText: { fontSize: 13, color: color(palette.muted, 'muted'), fontWeight: '500' },
  selectedTabText: { color: color(palette.green, 'accent'), fontWeight: '600' },
  loading: { padding: 6 },
  selection: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 16, paddingVertical: 4 },
  checkButton: { minHeight: 44, minWidth: 30, flexDirection: 'row', alignItems: 'center', gap: 8 },
  check: { width: 17, height: 17, borderRadius: 5, borderWidth: 1, borderColor: color('#cbd7d1', 'border'),
    backgroundColor: color('#fff', 'surface'), alignItems: 'center', justifyContent: 'center' },
  checked: { backgroundColor: color('#e5f2eb', 'elevated'), borderColor: color('#82b3a2', 'border') },
  treeIcon: { width: 20, height: 20, flexShrink: 0 },
  chevronSlot: { width: 12, alignItems: 'center', justifyContent: 'center' },
  meta: { fontSize: 10, lineHeight: 16, color: color(palette.muted, 'muted') },
  file: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16 },
  fileButton: { flex: 1, flexDirection: 'row', gap: 7, alignItems: 'center', minHeight: 44, paddingVertical: 8 },
  status: { fontSize: 10, lineHeight: 16, minWidth: 22, textAlign: 'center',
    paddingHorizontal: 4, borderRadius: 5, overflow: 'hidden' },
  folderCount: { color: color(palette.muted, 'muted') },
  conflict: { color: color(palette.danger, 'danger') },
  path: { fontSize: 13, lineHeight: 19, color: color(palette.ink, 'ink') },
  form: { paddingHorizontal: 16, paddingVertical: 10, gap: 8, borderTopWidth: 1, borderTopColor: color(palette.border, 'border') },
  input: { minHeight: 52, maxHeight: 100, textAlignVertical: 'top', color: color(palette.ink, 'ink'),
    borderWidth: 1, borderColor: color(palette.border, 'border'), backgroundColor: color('#fafcfb', 'surface'),
    borderRadius: 10, padding: 10, fontSize: 13 },
  hint: { maxWidth: 400, fontSize: 11, lineHeight: 16, color: color(palette.muted, 'muted') },
  submit: { padding: 12, alignItems: 'center', backgroundColor: palette.green, borderRadius: 8 },
  submitText: { fontSize: 13, fontWeight: '700', color: '#fff' },
  disabled: { opacity: .4 },
  detailTitle: { paddingHorizontal: 16, paddingVertical: 12, fontSize: 12, lineHeight: 18,
    color: color(palette.ink, 'ink'), backgroundColor: color('#f4f7f5', 'canvas') },
  commitHeading: { paddingHorizontal: 16, paddingVertical: 12, gap: 6 },
  commitFile: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 58,
    paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: color('#eef2ef', 'border') },
  commitStatus: { fontSize: 10, lineHeight: 16, paddingHorizontal: 6, paddingVertical: 2,
    borderRadius: 5, overflow: 'hidden' },
  diff: { fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace', fontSize: 11, lineHeight: 18,
    color: color(palette.ink, 'ink'), padding: 12 },
  added: { backgroundColor: color('#e8f5ec', 'canvas'), color: color('#166b40', 'accent') },
  removed: { backgroundColor: color('#ffeded', 'canvas'), color: color('#a73535', 'danger') },
  historyRow: { flexDirection: 'row', height: GRAPH_ROW_HEIGHT, alignItems: 'center' },
  historyText: { width: 310, gap: 4 },
  subject: { fontSize: 12, lineHeight: 18, color: color(palette.ink, 'ink'), fontWeight: '600' },
  refs: { flexDirection: 'row', gap: 4 },
  ref: { maxWidth: 230, fontSize: 10, lineHeight: 14, color: color(palette.green, 'accent'), backgroundColor: color('#e7f5ef', 'canvas'),
    borderRadius: 4, paddingHorizontal: 5, paddingVertical: 2 },
}));
