import { createThemedStyles } from '../theme/styles';
import { StyleSheet } from 'react-native';

export const colors = {
  ink: '#20332e', muted: '#7c8b86', green: '#087f69', blue: '#527cb4', danger: '#bd5454',
  canvas: '#f5f7f7', surface: '#ffffff', border: '#e5ece9', paleGreen: '#e8f4ef',
};

export const useStyles = createThemedStyles((color) => ({
  page: { flex: 1, backgroundColor: color(colors.canvas, 'canvas') },
  navigation: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, minHeight: 60,
    backgroundColor: color(colors.surface, 'surface'), borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: color(colors.border, 'border') },
  back: { width: 44, minHeight: 44, justifyContent: 'center', alignItems: 'center', borderRadius: 14 },
  pageTitle: { flex: 1, textAlign: 'center', color: color(colors.ink, 'ink'), fontSize: 18, fontWeight: '600' },
  list: { flex: 1 },
  listContent: { flexGrow: 1, padding: 20, paddingBottom: 32, width: '100%', maxWidth: 640, alignSelf: 'center' },
  sources: { gap: 14, marginBottom: 28 },
  connection: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  connectionDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.green },
  offlineDot: { backgroundColor: color(colors.muted, 'muted') },
  connectionName: { flexShrink: 1, fontSize: 13, color: color(colors.ink, 'ink') },
  caption: { fontSize: 11, lineHeight: 17, color: color(colors.muted, 'muted') },
  sectionLabel: { color: color(colors.muted, 'muted'), fontSize: 12, fontWeight: '500' },
  sourceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  sourceCard: { flex: 1, minWidth: 140, backgroundColor: color(colors.surface, 'surface'), borderRadius: 18,
    borderWidth: 1, borderColor: color(colors.border, 'border'), padding: 16, gap: 14 },
  sourceChevron: { position: 'absolute', right: 16, top: 29 },
  sourceIcon: { width: 42, height: 42, borderRadius: 13, backgroundColor: color(colors.paleGreen, 'accentSoft'),
    justifyContent: 'center', alignItems: 'center' },
  computerIcon: { backgroundColor: color('#edf2f9', 'canvas') },
  sourceCopy: { flexGrow: 1 },
  sourceTitle: { fontSize: 14, lineHeight: 22, fontWeight: '600', color: color(colors.ink, 'ink') },
  hint: { flexDirection: 'row', alignItems: 'flex-start', gap: 6 },
  hintText: { flex: 1, fontSize: 12, lineHeight: 18, color: color(colors.muted, 'muted') },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  sectionTitle: { fontSize: 16, fontWeight: '600', color: color(colors.ink, 'ink') },
  count: { fontSize: 12, color: color(colors.muted, 'muted') },
  empty: { alignItems: 'center', justifyContent: 'center', paddingVertical: 56, paddingHorizontal: 12,
    backgroundColor: color(colors.surface, 'surface'), borderRadius: 20, borderWidth: 1, borderColor: color(colors.border, 'border') },
  emptyHalo: { width: 96, height: 96, borderRadius: 48, backgroundColor: color('#f4f9f6', 'canvas'),
    justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
  emptyIcon: { width: 68, height: 68, borderRadius: 22, backgroundColor: color(colors.paleGreen, 'accentSoft'),
    justifyContent: 'center', alignItems: 'center' },
  emptyBadge: { position: 'absolute', right: 7, bottom: 10, width: 25, height: 25, borderRadius: 13,
    borderWidth: 3, borderColor: color(colors.surface, 'surface'), backgroundColor: colors.green,
    justifyContent: 'center', alignItems: 'center' },
  emptyTitle: { fontSize: 17, fontWeight: '600', color: color(colors.ink, 'ink'), marginBottom: 10 },
  emptyText: { fontSize: 12, lineHeight: 22, color: color(colors.muted, 'muted'), textAlign: 'center', maxWidth: 320 },
  card: { backgroundColor: color(colors.surface, 'surface'), borderRadius: 18, borderWidth: 1, borderColor: color(colors.border, 'border'),
    padding: 16, gap: 14, marginBottom: 12 },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  fileIcon: { width: 42, height: 46, borderRadius: 12, backgroundColor: color('#f0f5f3', 'canvas'),
    justifyContent: 'center', alignItems: 'center' },
  fileCopy: { flex: 1, gap: 5 },
  title: { color: color(colors.ink, 'ink'), fontSize: 15, lineHeight: 22, fontWeight: '600' },
  statusRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  status: { color: color(colors.green, 'accent'), fontSize: 11, fontWeight: '500' },
  statusBadge: { borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3, backgroundColor: color(colors.paleGreen, 'accentSoft') },
  pausedBadge: { backgroundColor: color('#f3f1eb', 'canvas') },
  paused: { color: color('#8f7b50', 'warning') },
  failedBadge: { backgroundColor: color('#fbeeee', 'canvas') },
  progressCopy: { gap: 8 },
  track: { height: 5, borderRadius: 4, backgroundColor: color('#edf2f0', 'elevated'), overflow: 'hidden' },
  progress: { height: '100%', backgroundColor: colors.green, borderRadius: 4 },
  pausedProgress: { backgroundColor: color('#b8a77e', 'elevated') },
  failedProgress: { backgroundColor: color(colors.danger, 'danger') },
  toolbar: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', alignItems: 'center' },
  cardActions: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: color(colors.border, 'border'),
    paddingTop: 12, justifyContent: 'space-between' },
  button: { minHeight: 44, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 14,
    borderRadius: 12, backgroundColor: color(colors.paleGreen, 'accentSoft'), flexDirection: 'row', gap: 6 },
  buttonText: { fontSize: 13, color: color(colors.green, 'accent'), fontWeight: '600' },
  deleteButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5,
    minHeight: 44, paddingHorizontal: 8, borderRadius: 10 },
  deleteText: { color: color(colors.muted, 'muted'), fontSize: 12 },
  danger: { color: color(colors.danger, 'danger') },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.65 },
  text: { fontSize: 13, lineHeight: 20, color: color(colors.muted, 'muted'), maxWidth: 400 },
  message: { fontSize: 13, lineHeight: 20, color: color(colors.green, 'accent'), maxWidth: 400, marginVertical: 8 },
  error: { fontSize: 13, lineHeight: 20, color: color(colors.danger, 'danger'), maxWidth: 400, marginVertical: 8 },
  browserHeader: { gap: 12, marginBottom: 20 },
  browserToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  path: { color: color(colors.ink, 'ink'), fontSize: 14, lineHeight: 22 },
  row: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14,
    backgroundColor: color(colors.surface, 'surface'), borderRadius: 14, borderWidth: 1, borderColor: color(colors.border, 'border'), marginBottom: 8 },
  name: { color: color(colors.ink, 'ink'), fontSize: 14, lineHeight: 21, flex: 1 },
}));
