import { expect, test } from '@playwright/test';
import { connect, fixtureUrl, login, openChatList, screenshot, state } from './chat-helpers';

test('tools open Git changes, commit only checked files and draw merge history', async ({ page, request }, info) => {
  await request.post(`${fixtureUrl}/test/reset`);
  await login(page); await connect(page); await openChatList(page);
  await page.getByRole('button', { name: '移动端聊天体验', exact: true }).click();
  await page.getByRole('button', { name: '打开工具', exact: true }).click();
  await expect(page.getByRole('button', { name: '终端', exact: true })).toBeVisible();
  await screenshot(page, info, 'tools-menu');
  await page.getByRole('button', { name: 'Git', exact: true }).click();
  const drawer = page.getByRole('dialog', { name: 'Git', exact: true });
  await expect(drawer).toBeVisible();
  const app = drawer.getByRole('checkbox', { name: '选择 src/app.ts', exact: true });
  await expect(app).toBeVisible();
  const folder = drawer.getByRole('checkbox', { name: '选择 src/chat', exact: true });
  await folder.check();
  await expect(drawer.getByRole('checkbox', { name: '选择 src/chat/tools.ts', exact: true })).toBeChecked();
  await expect(drawer.getByRole('checkbox', { name: '选择 src/chat/menu.ts', exact: true })).toBeChecked();
  await drawer.getByRole('button', { name: '平铺', exact: true }).click();
  await expect(folder).toHaveCount(0);
  await expect(drawer.getByRole('checkbox', { name: '选择 src/chat/tools.ts', exact: true })).toBeChecked();
  await screenshot(page, info, 'git-flat');
  await drawer.getByRole('button', { name: '文件夹', exact: true }).click();
  await folder.uncheck();
  await expect(drawer.locator('[data-area="unstaged"]')).not.toHaveCount(0);
  await expect(drawer.locator('[data-area="staged"]')).not.toHaveCount(0);
  await expect(drawer.locator('[data-area="mixed"]')).not.toHaveCount(0);
  await drawer.getByRole('button', { name: '展开或收起 src/chat', exact: true }).click();
  await expect(drawer.getByRole('checkbox', { name: '选择 src/chat/tools.ts', exact: true })).toHaveCount(0);
  await app.check();
  await drawer.getByRole('button', { name: '查看 src/app.ts', exact: true }).click();
  await expect(drawer.locator('.git-diff')).toContainText('+new code');
  await screenshot(page, info, 'git-diff');
  await drawer.getByRole('button', { name: 'src/app.ts', exact: true }).click();
  await expect(app).toBeChecked();
  const message = drawer.getByRole('textbox', { name: '提交说明' });
  await message.fill('更新应用');
  await screenshot(page, info, 'git-changes');
  await message.fill('fail');
  await drawer.getByRole('button', { name: '提交 1 个文件', exact: true }).click();
  await expect(drawer.getByRole('alert')).toContainText('暂时无法完成此操作');
  await expect(app).toBeChecked();
  await expect(message).toHaveValue('fail');
  await message.fill('更新应用');
  await drawer.getByRole('button', { name: '提交 1 个文件', exact: true }).click();
  await expect(drawer.getByRole('status')).toHaveText('已提交 8f17d63a');
  await expect(app).toHaveCount(0);
  await expect(drawer.getByRole('checkbox', { name: '选择 README.md', exact: true })).not.toBeChecked();
  const submitted = (await state(request)).operations.filter(op => op.operation === 'guiGitCommit').at(-1);
  expect(submitted?.files).toEqual([{ path: 'src/app.ts', version: 'app-v1' }]);
  await drawer.getByRole('tab', { name: '提交记录', exact: true }).click();
  await expect(drawer.locator('.git-history-row')).toHaveCount(3);
  await drawer.getByRole('button', { name: '加载更多提交' }).click();
  await expect(drawer.locator('.git-history-row')).toHaveCount(6);
  await expect(drawer.locator('.git-history svg circle')).toHaveCount(6);
  await expect(drawer.locator('.git-history svg line')).not.toHaveCount(0);
  await expect(drawer).toContainText('feature/git');
  await screenshot(page, info, 'git-history');
  const bounds = (await drawer.boundingBox())!;
  expect(bounds.width).toBeLessThanOrEqual(page.viewportSize()!.width);
  const diffCount = (await state(request)).operations.filter(op => op.operation === 'guiGitDiff').length;
  await drawer.locator('.git-history-row').nth(1).click();
  await expect(drawer.locator('.git-commit-file')).toHaveCount(4);
  await expect(drawer).toContainText('重命名');
  await expect(drawer).toContainText('docs/旧说明.md');
  await expect(drawer.locator('.git-diff')).toHaveCount(0);
  expect((await state(request)).operations.filter(op => op.operation === 'guiGitDiff')).toHaveLength(diffCount);
  await screenshot(page, info, 'git-commit-files');
  await drawer.getByRole('button', { name: '查看 src/chat/tools.ts', exact: true }).click();
  await expect(drawer.locator('.git-diff')).toContainText('committed change');
  await expect(drawer.locator('.git-diff')).toContainText('b/src/chat/tools.ts');
  const commitDiff = (await state(request)).operations.filter(op => op.operation === 'guiGitDiff').at(-1);
  expect(commitDiff).toMatchObject({ path: 'src/chat/tools.ts', commit: 'e950cd31'.padEnd(40, '5') });
  await screenshot(page, info, 'git-commit-file-diff');
  await drawer.getByRole('button', { name: '返回文件列表', exact: true }).click();
  await expect(drawer.locator('.git-commit-file')).toHaveCount(4);
  await drawer.getByRole('button', { name: '返回提交记录', exact: true }).click();
  await expect(drawer.locator('.git-history-row')).toHaveCount(6);
  await drawer.getByRole('button', { name: '切换分支', exact: true }).click();
  const branches = drawer.getByRole('region', { name: '切换分支', exact: true });
  await expect(branches.getByRole('button', { name: /release/ })).toBeDisabled();
  await screenshot(page, info, 'git-branches');
  await branches.getByRole('button', { name: 'feature/git 本地', exact: true }).click();
  await expect(drawer.getByRole('button', { name: '切换分支', exact: true })).toContainText('feature/git');
  await drawer.getByRole('button', { name: '同步', exact: true }).click();
  await expect(drawer.getByLabel('整合方式', { exact: true })).toHaveCount(0);
  await expect(drawer).toContainText('获取远程更新，无冲突时自动合并并提交。');
  await expect(drawer.getByRole('button', { name: '执行 更新项目', exact: true })).toBeDisabled();
  await drawer.getByRole('button', { name: '获取 Fetch', exact: true }).click();
  await drawer.getByRole('button', { name: '执行 获取 Fetch', exact: true }).click();
  await expect(drawer.getByRole('status')).toHaveText('已获取远程记录');
  await drawer.getByRole('tab', { name: /^改动/ }).click();
  await drawer.getByRole('checkbox', { name: '全选', exact: true }).check();
  await message.fill('完成剩余改动');
  await drawer.getByRole('button', { name: '提交 5 个文件', exact: true }).click();
  await expect(drawer).toContainText('工作区没有未提交的改动。');
  await drawer.getByRole('button', { name: '同步', exact: true }).click();
  await drawer.getByRole('button', { name: '拉取 Pull', exact: true }).click();
  await drawer.getByLabel('整合方式', { exact: true }).selectOption('rebase');
  await drawer.getByRole('button', { name: '更新项目', exact: true }).click();
  await expect(drawer.getByLabel('整合方式', { exact: true })).toHaveCount(0);
  expect((await drawer.locator('.git-menu').boundingBox())!.width).toBeLessThanOrEqual(400);
  await screenshot(page, info, 'git-update');
  await drawer.getByRole('button', { name: '执行 更新项目', exact: true }).click();
  await expect(drawer.getByRole('status')).toHaveText('项目已更新');
  await drawer.getByRole('button', { name: '同步', exact: true }).click();
  await drawer.getByRole('button', { name: '拉取 Pull', exact: true }).click();
  await drawer.getByLabel('整合方式', { exact: true }).selectOption('rebase');
  await drawer.getByRole('button', { name: '执行 拉取 Pull', exact: true }).click();
  await expect(drawer.getByRole('status')).toHaveText('拉取完成');
  await drawer.getByRole('button', { name: '同步', exact: true }).click();
  await drawer.getByRole('button', { name: '推送 Push', exact: true }).click();
  await drawer.getByRole('button', { name: '执行 推送 Push', exact: true }).click();
  await expect(drawer.getByRole('status')).toHaveText('推送完成');
  const actions = (await state(request)).operations.filter(op => op.operation === 'guiGitAction');
  expect(actions.map(op => op.action)).toEqual(['switch', 'fetch', 'update', 'pull', 'push']);
  expect(actions.find(op => op.action === 'update')?.strategy).toBe('merge');
  expect(actions.find(op => op.action === 'pull')?.strategy).toBe('rebase');
  await drawer.getByRole('button', { name: '关闭 Git' }).click();
  await page.getByRole('button', { name: '打开工具', exact: true }).click();
  await page.getByRole('button', { name: '终端', exact: true }).click();
  await expect(page.getByRole('dialog', { name: '远程终端', exact: true })).toBeVisible();
  await expect(page.locator('.xterm-rows')).toContainText('Remote shell ready');
});
