import type { Account, AppInfo } from "./types";

export const DEMO_ACCOUNTS: Account[] = [
  {
    id: "demo-1",
    email: "alex.chen@example.com",
    group: "",
    note: "Personal account for experiments and everyday Codex work.",
    expiresAt: "2026-12-31",
    privateDetails: { password: "", phoneNumber: "", totpSecret: "" },
    plan: "Plus",
    active: true,
    autoSwitchEnabled: true,
    autoSwitchPriority: 0,
    autoSwitchThreshold: 0,
    localProxyCompatible: true,
    directSwitchCompatible: false,
    agentIdentity: true,
    official: true,
    metadataEditable: false,
    accountId: "workspace-personal",
    usage: {
      primary: { usedPercent: 28, remainingPercent: 72, resetsAt: Date.now() / 1000 + 8200 },
      secondary: { usedPercent: 43, remainingPercent: 57, resetsAt: Date.now() / 1000 + 238000 },
      credits: { hasCredits: true, unlimited: false, balance: "62500" },
      fetchedAt: new Date().toISOString(),
    },
  },
  {
    id: "demo-2",
    email: "studio@northwind.dev",
    group: "",
    note: "",
    expiresAt: "",
    privateDetails: { password: "", phoneNumber: "", totpSecret: "" },
    plan: "Business",
    active: false,
    autoSwitchEnabled: false,
    autoSwitchPriority: 0,
    autoSwitchThreshold: 0,
    localProxyCompatible: true,
    directSwitchCompatible: true,
    agentIdentity: false,
    official: false,
    metadataEditable: true,
    accountId: "workspace-studio",
    usage: {
      credits: { hasCredits: false, unlimited: false, balance: "0" },
      primary: { usedPercent: 64, remainingPercent: 36, resetsAt: Date.now() / 1000 + 4500 },
      secondary: { usedPercent: 19, remainingPercent: 81, resetsAt: Date.now() / 1000 + 410000 },
      fetchedAt: new Date(Date.now() - 12 * 60_000).toISOString(),
    },
  },
  {
    id: "demo-3",
    email: "studio@northwind.dev",
    group: "",
    note: "",
    expiresAt: "",
    privateDetails: { password: "", phoneNumber: "", totpSecret: "" },
    plan: "Business",
    active: false,
    autoSwitchEnabled: false,
    autoSwitchPriority: 0,
    autoSwitchThreshold: 0,
    localProxyCompatible: true,
    directSwitchCompatible: true,
    agentIdentity: false,
    official: false,
    metadataEditable: true,
    accountId: "workspace-studio",
    usage: {
      primary: { usedPercent: 64, remainingPercent: 36, resetsAt: Date.now() / 1000 + 4500 },
      secondary: { usedPercent: 19, remainingPercent: 81, resetsAt: Date.now() / 1000 + 410000 },
      fetchedAt: new Date(Date.now() - 12 * 60_000).toISOString(),
    },
  },
  {
    id: "demo-4",
    email: "studio@northwind.dev",
    group: "",
    note: "",
    expiresAt: "",
    privateDetails: { password: "", phoneNumber: "", totpSecret: "" },
    plan: "Business",
    active: false,
    autoSwitchEnabled: false,
    autoSwitchPriority: 0,
    autoSwitchThreshold: 0,
    localProxyCompatible: true,
    directSwitchCompatible: true,
    agentIdentity: false,
    official: false,
    metadataEditable: true,
    accountId: "workspace-studio",
    usage: {
      primary: { usedPercent: 64, remainingPercent: 36, resetsAt: Date.now() / 1000 + 4500 },
      secondary: { usedPercent: 19, remainingPercent: 81, resetsAt: Date.now() / 1000 + 410000 },
      fetchedAt: new Date(Date.now() - 12 * 60_000).toISOString(),
    },
  },
];

export const DEMO_INFO: AppInfo = {
  codexHome: "~/.codex",
  authPath: "~/.codex/auth.json",
  configPath: "~/.codex/config.toml",
  accountStore: "~/.local/share/codex-switch/accounts",
  providerStore: "~/.local/share/codex-switch/providers",
  version: "0.1.0",
};
